# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHHkMXDHVtWCjaTJwYqzHbD4YnPR0HGY
"""

# =====================================
# 0. Colab 환경이면 자동 설치
# =====================================
try:
    import google.colab
    IN_COLAB = True
    !pip install konlpy pandas matplotlib numpy ipywidgets
except:
    IN_COLAB = False

# =====================================
# 1. 라이브러리
# =====================================
from konlpy.tag import Okt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

okt = Okt()

# =====================================
# 2. 핵심 분석 함수 (공통)
# =====================================
def speech_analysis(utterances):
    results = []
    total_morphemes = 0
    total_words = 0
    vocab_set = set()
    utterance_lengths = []

    for utt in utterances:
        morphs = okt.morphs(utt)
        words = utt.split()

        total_morphemes += len(morphs)
        total_words += len(words)
        vocab_set.update(morphs)

        utterance_lengths.append(len(morphs))

        results.append({
            "발화": utt,
            "어절 수": len(words),
            "형태소 수": len(morphs)
        })

    df = pd.DataFrame(results)

    MLU = total_morphemes / len(utterances)
    TTR = len(vocab_set) / total_morphemes

    summary = {
        "총 발화 수": len(utterances),
        "총 어절 수": total_words,
        "총 형태소 수": total_morphemes,
        "MLU": round(MLU, 2),
        "TTR": round(TTR, 2)
    }

    return df, summary, utterance_lengths


# =====================================
# 3. 실행 함수 (공통)
# =====================================
def run_analysis(utterances):
    df, summary, lengths = speech_analysis(utterances)

    return df, summary, lengths


# =====================================
# 4. Streamlit 실행
# =====================================
if not IN_COLAB:
    try:
        import streamlit as st

        st.title("🗣️ 발화 자동 분석기")

        text = st.text_area("문장 입력 (한 줄에 하나씩)", "")

        if st.button("분석 실행"):
            if text.strip() == "":
                st.warning("문장을 입력하세요")
            else:
                utterances = [s.strip() for s in text.split("\n") if s.strip()]

                df, summary, lengths = run_analysis(utterances)

                st.subheader("📊 분석 결과")
                st.dataframe(df)

                st.subheader("📈 요약")
                st.write(summary)

                fig, ax = plt.subplots()
                ax.bar(range(len(lengths)), lengths)
                st.pyplot(fig)

    except:
        pass


# =====================================
# 5. Colab 실행 (UI 포함)
# =====================================
if IN_COLAB:
    import ipywidgets as widgets
    from IPython.display import display, clear_output

    text_input = widgets.Textarea(
        placeholder="한 줄에 한 문장씩 입력하세요",
        layout={'width': '80%', 'height': '150px'}
    )

    button = widgets.Button(description="분석 실행", button_style='success')
    output = widgets.Output()

    def on_click(b):
        with output:
            clear_output()

            text = text_input.value.strip()
            if not text:
                print("문장을 입력하세요")
                return

            utterances = [s.strip() for s in text.split("\n") if s.strip()]

            df, summary, lengths = run_analysis(utterances)

            print("📊 분석 결과")
            display(df)

            print("\n📈 요약")
            for k, v in summary.items():
                print(f"{k}: {v}")

            plt.figure()
            plt.bar(range(len(lengths)), lengths)
            plt.title("발화 길이")
            plt.show()

    button.on_click(on_click)
    display(text_input, button, output)