# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmQfCLXYL0Wa6e_KNB_lS-KHNefFFw4L
"""

# app.py 파일 생성
code = """# -*- coding: utf-8 -*-

import streamlit as st
from konlpy.tag import Okt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

okt = Okt()

def speech_analysis(utterances):
    results = []
    total_morphemes = 0
    total_words = 0
    vocab_set = set()
    utterance_lengths = []

    for utt in utterances:
        morphs = okt.morphs(utt)
        words = utt.split()

        total_morphemes += len(morphs)
        total_words += len(words)
        vocab_set.update(morphs)

        utterance_lengths.append(len(morphs))

        results.append({
            "발화": utt,
            "어절 수": len(words),
            "형태소 수": len(morphs)
        })

    df = pd.DataFrame(results)

    MLU = total_morphemes / len(utterances)
    TTR = len(vocab_set) / total_morphemes

    summary = {
        "총 발화 수": len(utterances),
        "총 어절 수": total_words,
        "총 형태소 수": total_morphemes,
        "MLU": round(MLU, 2),
        "TTR": round(TTR, 2)
    }

    return df, summary, utterance_lengths


st.title("🗣️ 발화 자동 분석기")

text = st.text_area("문장 입력 (한 줄에 하나씩)", "")

if st.button("분석 실행"):
    if text.strip() == "":
        st.warning("문장을 입력하세요")
    else:
        utterances = [s.strip() for s in text.split("\\n") if s.strip()]

        df, summary, lengths = speech_analysis(utterances)

        st.subheader("📊 분석 결과")
        st.dataframe(df)

        st.subheader("📈 요약")
        st.write(summary)

        st.subheader("📊 그래프")
        fig, ax = plt.subplots()
        ax.bar(range(len(lengths)), lengths)
        st.pyplot(fig)
"""

# 파일 저장
with open("app.py", "w") as f:
    f.write(code)

# 다운로드
from google.colab import files
files.download("app.py")

pip install streamlit konlpy

"""## Streamlit 앱 실행 및 배포

위 셀에서 `app.py` 파일을 다운로드했습니다. 이 파일을 로컬 컴퓨터에 저장한 후 다음 단계를 따르세요:

1.  **필요한 라이브러리 설치 (로컬 환경에서):**
    ```bash
    pip install streamlit konlpy
    ```

2.  **Streamlit 앱 실행:**
    터미널 또는 명령 프롬프트를 열고 `app.py` 파일이 있는 디렉토리로 이동한 후 다음 명령어를 실행합니다.
    ```bash
    streamlit run app.py
    ```
    이 명령어를 실행하면 웹 브라우저에서 Streamlit 앱이 자동으로 열립니다.

3.  **웹 배포 (선택 사항):**
    Streamlit 앱을 웹에 배포하려면 [Streamlit Community Cloud](https://streamlit.io/cloud)와 같은 서비스를 이용할 수 있습니다. 일반적으로 GitHub 저장소에 코드를 업로드한 후 해당 서비스와 연동하여 배포합니다.

"""