# -*- coding: utf-8 -*-
"""자동 발화분석.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNQmHnZAzDxP3GFSsLATbTBWHRIk0bmz
"""

# =====================================
# 1. 설치
# =====================================
!pip install konlpy pandas matplotlib numpy

# =====================================
# 2. 라이브러리 로드
# =====================================
from konlpy.tag import Okt
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

okt = Okt()

# =====================================
# 3. 발화 입력 (여기에 데이터 넣기)
# =====================================
utterances = [
    "새로운 문장입니다",
    "여기에 당신의 문장을 추가하세요"
]

# =====================================
# 4. 핵심 자동 분석 함수
# =====================================
def speech_analysis(utterances):
    results = []

    total_morphemes = 0
    total_words = 0
    vocab_set = set()

    utterance_lengths = []

    for utt in utterances:
        morphs = okt.morphs(utt)
        words = utt.split()

        total_morphemes += len(morphs)
        total_words += len(words)
        vocab_set.update(morphs)

        utterance_lengths.append(len(morphs))

        results.append({
            "발화": utt,
            "어절 수": len(words),
            "형태소 수": len(morphs)
        })

    df = pd.DataFrame(results)

    # ==============================
    # 5. 핵심 지표 자동 계산
    # ==============================
    MLU = total_morphemes / len(utterances)  # 평균 발화 길이 (형태소 기준)
    MLU_word = total_words / len(utterances) # 어절 기준 평균 발화 길이
    TTR = len(vocab_set) / total_morphemes   # 어휘 다양도

    summary = {
        "총 발화 수": len(utterances),
        "총 어절 수": total_words,
        "총 형태소 수": total_morphemes,
        "MLU (형태소 기준)": round(MLU, 2),
        "MLU (어절 기준)": round(MLU_word, 2),
        "TTR (어휘 다양도)": round(TTR, 2),
        "최대 발화 길이": max(utterance_lengths),
        "최소 발화 길이": min(utterance_lengths),
        "평균 발화 길이": round(np.mean(utterance_lengths), 2)
    }

    return df, summary, utterance_lengths

df, summary, lengths = speech_analysis(utterances)

# =====================================
# 6. 결과 출력
# =====================================
print("📊 발화별 분석 결과")
display(df)

print("\n📈 전체 자동 분석 지표")
for k, v in summary.items():
    print(f"{k}: {v}")

# =====================================
# 7. 시각화 (발화 길이 분포)
# =====================================
plt.figure(figsize=(8,4))
plt.bar(range(len(lengths)), lengths)
plt.xticks(range(len(lengths)), [f"U{i+1}" for i in range(len(lengths))])
plt.title("발화별 형태소 길이")
plt.ylabel("길이")
plt.show()

# =====================================
# 8. 치료용 자동 해석 (간단 피드백)
# =====================================
print("\n🧠 자동 해석")

if summary["MLU (형태소 기준)"] < 3:
    print("- 발화 길이가 짧은 편 → 문장 확장 훈련 필요")
elif summary["MLU (형태소 기준)"] < 5:
    print("- 중간 수준 발화 → 문장 구조 확장 가능")
else:
    print("- 비교적 긴 발화 → 문장 구성 양호")

if summary["TTR (어휘 다양도)"] < 0.4:
    print("- 어휘 다양도 낮음 → 다양한 단어 노출 필요")
else:
    print("- 어휘 다양도 양호")

print("\n✅ 분석 완료")

# -*- coding: utf-8 -*-
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

print("한글 폰트 설정 완료. 런타임을 다시 시작하고 코드를 다시 실행해주세요.")

"""## 🗣️ 새로운 문장 입력 및 분석

아래 텍스트 상자에 분석하고 싶은 문장들을 한 줄에 하나씩 입력해주세요. 입력 후 '분석 실행' 버튼을 누르면 입력된 문장들에 대한 발화 분석을 수행하고 결과를 보여줍니다.
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

# 텍스트 입력 위젯 생성
text_input = widgets.Textarea(
    value='',
    placeholder='여기에 분석할 문장들을 입력하세요 (한 줄에 한 문장)',
    description='문장 입력:',
    disabled=False,
    layout={'height': '150px', 'width': '80%'}
)

# 분석 실행 버튼 생성
analyze_button = widgets.Button(
    description='분석 실행',
    disabled=False,
    button_style='success', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='입력된 문장으로 발화 분석을 실행합니다.'
)

output_area = widgets.Output()

# 버튼 클릭 시 실행될 함수
def on_button_clicked(b):
    with output_area:
        clear_output(wait=True)
        input_sentences_raw = text_input.value.strip()
        if not input_sentences_raw:
            print("분석할 문장이 없습니다. 문장을 입력해주세요.")
            return

        # 입력된 텍스트를 문장 리스트로 변환 (줄바꿈 기준으로 분리)
        input_utterances = [s.strip() for s in input_sentences_raw.split('\n') if s.strip()]

        if not input_utterances:
            print("분석할 문장이 없습니다. 문장을 입력해주세요.")
            return

        # 기존 speech_analysis 함수 호출
        df_new, summary_new, lengths_new = speech_analysis(input_utterances)

        # 결과 출력 (기존 코드 재활용)
        print("📊 발화별 분석 결과")
        display(df_new)

        print("\n📈 전체 자동 분석 지표")
        for k, v in summary_new.items():
            print(f"{k}: {v}")

        print("\n")

        # 시각화 (발화 길이 분포) - 한글 폰트 설정이 되어있다고 가정
        plt.figure(figsize=(8,4))
        plt.bar(range(len(lengths_new)), lengths_new)
        plt.xticks(range(len(lengths_new)), [f"U{i+1}" for i in range(len(lengths_new))])
        plt.title("발화별 형태소 길이")
        plt.ylabel("길이")
        plt.show()

        # 치료용 자동 해석 (간단 피드백)
        print("\n🧠 자동 해석")
        if summary_new["MLU (형태소 기준)"] < 3:
            print("- 발화 길이가 짧은 편 → 문장 확장 훈련 필요")
        elif summary_new["MLU (형태소 기준)"] < 5:
            print("- 중간 수준 발화 → 문장 구조 확장 가능")
        else:
            print("- 비교적 긴 발화 → 문장 구성 양호")

        if summary_new["TTR (어휘 다양도)"] < 0.4:
            print("- 어휘 다양도 낮음 → 다양한 단어 노출 필요")
        else:
            print("- 어휘 다양도 양호")

        print("\n✅ 분석 완료")

# 버튼에 콜백 함수 연결
analyze_button.on_click(on_button_clicked)

# 위젯들을 화면에 표시
display(text_input, analyze_button, output_area)